artifact_location: file:///C:/Users/NITRO V15/Desktop/My_folder/projects/numberplate_recognition/runs/mlflow/671191732614852789
creation_time: 1772183268706
experiment_id: '671191732614852789'
last_update_time: 1772183268706
lifecycle_stage: active
name: runs
workspace: default
