artifact_location: file:///C:/Users/NITRO V15/Desktop/My_folder/projects/numberplate_recognition/runs/mlflow/0
creation_time: 1772183268643
experiment_id: '0'
last_update_time: 1772183268643
lifecycle_stage: active
name: Default
workspace: default
